<RedactFilmMenu>:
    
    status_button: status_button 
    film_name_txt: film_name_txt
    film_genre_txt: film_genre_txt
    film_description_txt: film_description_txt
    rating_layout: rating_layout
    
    canvas:
        Color: 
            rgb : 1, 1, 1
        Rectangle: 
            pos: 0,0
            size: root.width, root.height
        Color:
            rgb: 167/255, 115/255, 187/255
        Rectangle:
            pos: 0, 0
            size: root.width /6 , root.height
        Rectangle:
            pos: root.width * 5/6, 0
            size: root.width * 1 / 6 , root.height
        Rectangle:
            pos: root.width/6, root.height - root.height/8
            size: root.width * 4 /6,  root.height / 8
        Color:
            rgba: 230/255, 230/255, 230/255, 1
        RoundedRectangle:
            size: root.width/10*2, root.height/10* 0.35
            pos: root.width/10*2.9, root.height/ 10 * 8.07
            radius: [15,]
        RoundedRectangle:
            size: root.width/10*2, root.height/10* 0.35
            pos: root.width/10*2.55, root.height/ 10 * 7.42
            radius: [15,]
        RoundedRectangle:
            pos: root.width / 10 * 1.9, root.height/10*0.5
            size: root.width/10 * 6, root.height/10*4.8
            radius: [15,]
    Label:
        font_size: 100
        size_hint: 2.53/10, 0.7/10
        pos_hint: {"x": 1/4.4, "y": 17.8/20}
        text: "Redact-film"
        font_name: "FreeCheese"
        canvas.before:
            Color:
                rgba: 1, 0, 0, 0 
            Rectangle:
                pos: self.pos
                size: self.size
    CustomButtonWith2States:
        mipmap: True
        fit_mode: "fill"
        size_hint: 0.55/10, 0.98/10
        pos_hint: {"x": 8.4/10, "y": 0.1/10}
        normal_source: root.normal_apl_res
        down_source: root.down_apl_res
        on_release:root.save_changes()
    CustomButtonWith2States:
        mipmap: True
        fit_mode: "fill"
        size_hint: 0.55/10, 0.98/10
        pos_hint: {"x": 9.02/10, "y": 0.1/10}
        normal_source: root.normal_get_back_res
        down_source: root.down_get_back_res
        on_release:root.getBackOnRelease()
    
    Label:
        color: (136/255,136/255,136/255)
        font_size: 30
        size_hint: 1/10, 0.3/10
        pos_hint: {"x": 1/5.5, "y": 8.1/10}
        text: "Название:"
        font_name: "Guidy"
    Label:
        color: (136/255,136/255,136/255)
        text: 'Жанр:'
        font_name: "Guidy"
        font_size: 30
        size_hint: 0.5/10, 0.3/10
        pos_hint: {"x": 1.91/10, "y": 7.45/10}
    Label:
        color: (136/255,136/255,136/255)
        text: 'Статус:'
        font_name: "Guidy"
        font_size: 30
        size_hint: 0.5/10, 0.3/10
        pos_hint: {"x": 1.93/10, "y": 6.84/10}
    Label:
        color: (136/255,136/255,136/255)
        text: 'Рейтинг:'
        font_name: "Guidy"
        font_size: 30
        size_hint: 0.7/10, 0.3/10
        pos_hint: {"x": 1.9/10, "y": 6.23/10}
    Label:
        color: (136/255,136/255,136/255)
        text: 'Комментарий:'
        font_name: "Guidy"
        font_size: 30
        size_hint: 1.2/10, 0.3/10
        pos_hint: {"x": 1.87/10, "y": 5.62/10}
    
    TextInput:
        id: film_name_txt
        text: ''
        multiline: False
        font_name: "Guidy"
        pos_hint: {"x": 2.92/10, "y": 8.07/10}
        size_hint: 2/10, 0.35/10
        font_size: sp(25)
        background_color: 1, 1, 1, 0
        foreground_color: 0, 0, 0, 1

    TextInput:
        id: film_genre_txt
        text: ''
        multiline: False
        font_name: "Guidy"
        pos_hint: {"x": 2.57/10, "y": 7.42/10}
        size_hint: 2/10, 0.35/10
        font_size: sp(25)
        background_color: 1, 1, 1, 0
        foreground_color: 0, 0, 0, 1
    
    Button:
        id: status_button
        background_color: 0, 0, 0, 0  
        canvas.before:
            Color:
                rgba: 136/255,136/255,136/255, 1  
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [15,]
        text: 'Все'
        size_hint: 0.78/10, 0.3/10
        background_normal: ''
        color: 1, 1, 1, 1
        font_name: "Guidy"
        font_size: 20
        pos_hint: {"x": 2.6/10, "y": 6.84/10}
        on_release: root.open_status_dropdown()

    CustomLayotForRating:
        id:rating_layout
        pos_hint: {"x": 2.7/10, "y": 6.25/10}
        on_selected_rating: root.on_rating_selected(args[1])
    TextInput:
        id: film_description_txt
        text: ''
        font_name: "Guidy"
        pos_hint: {"x": 1.95/10, "y": 0.5/10}
        size_hint: 5.9/10, 4.8/10
        font_size: sp(25)
        background_color: 230/255, 230/255, 230/255, 0
        foreground_color: 0, 0, 0, 1
<redactFilmMenuScreen>:
    
    name: "redactFilmMenuScreen"
    RedactFilmMenu:
        id: redact_film_menu