
<RedactFilmMenu>:
    
    status_button: status_button 
    film_name_txt: film_name_txt
    film_genre_txt: film_genre_txt
    film_description_txt: film_description_txt
    rating_layout: rating_layout
    
    canvas:
        Color: 
            rgb : 1, 1, 1
        Rectangle: 
            pos: 0,0
            size: root.width, root.height
        Color:
            rgb: 167/255, 115/255, 187/255
        Rectangle:
            pos: 0, 0
            size: root.width /6 , root.height
        Rectangle:
            pos: root.width * 5/6, 0
            size: root.width * 1 / 6 , root.height
        Rectangle:
            pos: root.width/6, root.height - root.height/8
            size: root.width * 4 /6,  root.height / 8
        Color:
            rgba: 230/255, 230/255, 230/255, 1
        RoundedRectangle:
            size: root.width/10*2, root.height/10* 0.35
            pos: root.width/10*2.9, root.height/ 10 * 8.07
            radius: [15,]
        RoundedRectangle:
            size: root.width/10*2, root.height/10* 0.35
            pos: root.width/10*2.55, root.height/ 10 * 7.42
            radius: [15,]
        RoundedRectangle:
            pos: root.width / 10 * 1.9, root.height/10*0.5
            size: root.width/10 * 6, root.height/10*4.8
            radius: [15,]
    Label:
        font_size: 100
        size_hint: None, None
        size: root.width/10*2.53, root.height/10* .7
        center: root.center
        pos: root.width/4.4,  root.height/20 * 17.8
        text: "Redact-film"
        font_name: "FreeCheese"
        canvas.before:
            Color:
                rgba: 1, 0, 0, 0 
            Rectangle:
                pos: self.pos
                size: self.size
    CustomButtonWith2States:
        size_hint: (None, None)
        
        mipmap: True
        fit_mode: "fill"
        size: root.width/10* 0.55, root.height/10 * 0.98
        pos: root.width/10 * 8.4, root.height/10 * 0.1
        normal_source: root.normal_apl_res
        down_source: root.down_apl_res

        on_release:root.save_changes()
    CustomButtonWith2States:
        size_hint: (None, None)
        
        mipmap: True
        fit_mode: "fill"
        size: root.width/10* 0.55, root.height/10 * 0.98
        pos: root.width/10 * 9.02, root.height/10 * 0.1
        normal_source: root.normal_get_back_res
        down_source: root.down_get_back_res
        on_release:root.getBackOnRelease()
    
    Label:
        color: (136/255,136/255,136/255)
        font_size: 30
        size_hint: None, None
        size: root.width/10*1, root.height/10*0.3
        center: root.center
        pos: root.width/5.5,  root.height/10* 8.1
        text: "Название:"
        font_name: "Guidy"
    Label:
        color: (136/255,136/255,136/255)
        text: 'Жанр:'
        font_name: "Guidy"
        font_size: 30
        size_hint: None, None
        center: root.center
        size: root.width/10*0.5, root.height/10*0.3
        pos: root.width / 10 * 1.91, root.height/10 * 7.45
    Label:
        color: (136/255,136/255,136/255)
        text: 'Статус:'
        font_name: "Guidy"
        font_size: 30
        size_hint: None, None
        center: root.center
        size: root.width/10*0.5, root.height/10*0.3
        pos: root.width / 10 * 1.93, root.height/10 * 6.84
    Label:
        color: (136/255,136/255,136/255)
        text: 'Рейтинг:'
        font_name: "Guidy"
        font_size: 30
        size_hint: None, None
        center: root.center
        size: root.width/10*0.7, root.height/10*0.3
        pos: root.width / 10 * 1.9, root.height/10 * 6.23
    Label:
        color: (136/255,136/255,136/255)
        text: 'Комментарий:'
        font_name: "Guidy"
        font_size: 30
        size_hint: None, None
        center: root.center
        size: root.width/10 * 1.2, root.height/10*0.3
        pos: root.width / 10 * 1.87, root.height/10 * 5.62
    
    TextInput:
        id: film_name_txt
        text: ''
        multiline: False
        size_hint: None, None
        pos:  root.width/10*2.92, root.height/ 10 * 8.07
        size: root.width/10*2, root.height/10* 0.35
        font_size: 20
        background_color: 1, 1, 1, 0
        foreground_color: 0, 0, 0, 1

    TextInput:
        id: film_genre_txt
        text: ''
        multiline: False
        size_hint: None, None
        pos: root.width/10*2.57, root.height/ 10 * 7.42
        size: root.width/10*2, root.height/10* 0.35
        font_size: 20
        background_color: 1, 1, 1, 0
        foreground_color: 0, 0, 0, 1
    
    Button:
        id: status_button
        background_color: 0, 0, 0, 0  
        canvas.before:
            Color:
                rgba: 136/255,136/255,136/255, 1  
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [15,]
        text: 'Все'
        size_hint: None, None
        size: root.width/10*0.78, root.height/10 * 0.3
        background_normal: ''
        color: 1, 1, 1, 1
        font_name: "Guidy"
        font_size: 20
        pos: root.width / 10 * 2.6  , root.height/10 * 6.84
        on_release: root.open_status_dropdown()

    CustomLayotForRating:
        id:rating_layout
        pos: root.width /10 * 2.7, root.height/10 * 6.25
        on_selected_rating: root.on_rating_selected(args[1])
    TextInput:
        id: film_description_txt
        text: ''
        size_hint: None, None
        pos: root.width / 10 * 1.95, root.height/10*0.5
        size: root.width/10 * 5.9, root.height/10*4.8
        font_size: 20
        background_color: 230/255, 230/255, 230/255, 0
        foreground_color: 0, 0, 0, 1
<redactFilmMenuScreen>:
    
    name: "redactFilmMenuScreen"
    RedactFilmMenu:
        id: redact_film_menu
        