<ExportImportMenu>:
    container_dyn:container_dyn
    
    canvas: 
        Color: 
            rgba: 1,1,1,1
        Rectangle: 
            size: self.size
        Color:
            rgb: 167/255, 115/255, 187/255
            # rgb: 1, 1, 1
        Rectangle:
            pos: 0, 0
            size: root.width /6 , root.height
        Rectangle:
            pos: root.width * 5/6, 0
            size: root.width * 1 / 6 , root.height
        Rectangle:
            pos: root.width/6, root.height - root.height/8
            size: root.width * 4 /6,  root.height / 8
    Label:
        font_size: '100sp'
        pos_hint: {'x': 1/5.2, 'y': 8.8/10}
        size_hint: None, None
        size: self.texture_size
        text: "Export/import"
        font_name: "FreeCheese"
    CustomButtonWith2States:
        size_hint: 0.55/10, 0.98/10
        mipmap: True
        fit_mode: "fill"
        pos_hint: {'x': 1.04/10, 'y': 0.1/10}
        normal_source: root.normal_home_res
        down_source: root.down_home_res
        on_release: root.go_to_home()

    BoxLayout:
        pos_hint: {'x': 1.665/10, 'y': 7.5/10}
        size_hint: 6.67/10, 3/10
        orientation: 'vertical'
        Widget:
            size_hint: 1, 0.5
        BoxLayout:
            pos_hint: {'x': 2.5/10, 'y': 1}
            orientation: 'horizontal'
            size_hint: 0.5, 1
            Button:
                background_color: 0, 0, 0, 0  # Прозрачный фон
                canvas.before:
                    Color:
                        rgba: 136/255,136/255,136/255, 1  # Цвет кнопки
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(50),]
                size_hint: (0.5, 0.3)
                pos_hint: {'center_x': 0.5}
                background_normal: ''
                color: 1, 1, 1, 1
                font_name: "Guidy"
                font_size: '40sp'
                text: "Экспорт"
                on_press:
                    self.canvas.before.children[0].rgba = (136/255, 136/255, 212/255, 1)
                on_release:
                    self.canvas.before.children[0].rgba = (136/255, 136/255, 136/255, 1)
                    root.spawn_export_widgets()
            Widget:
                size_hint: 0.05, 1
            Button:
                background_color: 0, 0, 0, 0  # Прозрачный фон
                canvas.before:
                    Color:
                        rgba: 136/255,136/255,136/255, 1  # Цвет кнопки
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(50),]
                size_hint: (0.5, 0.3)
                pos_hint: {'center_x': 0.5}
                background_normal: ''
                color: 1, 1, 1, 1
                font_name: "Guidy"
                font_size: '40sp'
                text: "Импорт"
                on_press:
                    self.canvas.before.children[0].rgba = (136/255, 136/255, 212/255, 1)
                on_release:
                    self.canvas.before.children[0].rgba = (136/255, 136/255, 136/255, 1)
    BoxLayout:
        id: container_dyn
        pos_hint: {'x': 1.665/10, 'y': 4/10}
        size_hint: 6.67/10, 3/10
        orientation: 'vertical'
        
        canvas.before:
            Color:
                rgba: 1, 0, 0, 1
            Rectangle:
                pos: self.pos
                size: self.size
        
<exportImportScreen>:
    name: "exportImportScreen"
    ExportImportMenu:
        id: export_import_menu
            