<FillistMainMenu>:
    
    canvas:
        Color: 
            rgb : 1, 1, 1
        Rectangle: 
            pos: 0,0
            size: root.width, root.height
        Color:
            rgb: 167/255, 115/255, 187/255
        Rectangle:
            pos: 0, 0
            size: root.width /6 , root.height
        Rectangle:
            pos: root.width * 5/6, 0
            size: root.width * 1 / 6 , root.height
        Rectangle:
            pos: root.width/6, root.height - root.height/8
            size: root.width * 4 /6,  root.height / 8
    Label:
        font_size: '100sp'
        pos_hint: {'x': 1/5.2, 'y': 8.8/10}
        size_hint: None, None
        size: self.texture_size
        text: "F i l l i s t"
        font_name: "FreeCheese"
    myLayout:
        pos_hint: {'x': 1.67/10, 'y': 0}
        size_hint: 6.67/10, 8.75/10
        

    CustomButtonToGoToOtherScreen:
        size_hint: 0.55/10, 0.98/10
        mipmap: True
        fit_mode: "fill"
        pos_hint: {'x': 8.4/10, 'y': 0.1/10}
        on_release: root.go_to_addScreen()

<mainScreen>:
    name: "mainScreen"
    FillistMainMenu:
        id: fillist_main_menu