
<myLayout>:
    
    search_text: search_text
    status_button: status_button 
    rating_layout: rating_layout 
    scroll_menu: scroll_menu
    genre_search_text: genre_search_text
    canvas: 
        Rectangle: 
            pos: self.pos
            size: self.size
        Color:
            rgba: 230/255, 230/255, 230/255, 1
        RoundedRectangle:
            pos: root.width/ 10*2.9, root.height/10 *9.3
            size: root.width/10*9.2, root.height/10*0.4
            radius: [15,]
        RoundedRectangle:
            pos: root.width/ 10*4, root.height/10 *7.22
            size: root.width/10*2, root.height/10*0.4
            radius: [15,]
    
    Label:
        color: (136/255,136/255,136/255)
        font_size: 25
        size_hint: None, None
        size: root.width/10, root.height/10 * 0.4
        text: 'Статус:'
        pos: root.width / 10 * 2.77 ,root.height/10 * 8.11
        font_name: "Guidy"
        
        canvas.before:
            Color:
                rgba: 1, 0, 0, 0 
            Rectangle:
                pos: self.pos
                size: self.size
    Label:
        color: (136/255,136/255,136/255)
        font_size: 25
        text: 'Рейтинг:'
        size_hint: None, None
        size: root.width/10, root.height/10 * 0.4
        pos: root.width / 10 * 2.85 , root.height/10 * 7.65
        font_name: "Guidy"
    

    TextInput:
        id: search_text
        background_color: 0, 0, 0, 0  # Прозрачный фон самого TextInput
        foreground_color: 0, 0, 0, 1  # Цвет текста - черный
        cursor_color: 0, 0, 0, 1  # Цвет курсора
        padding: [10, 6]  # Отступы для текста
        multiline: False

        hint_text: "Поиск..."
        hint_text_color: 136/255, 136/255, 136/255, 1
        font_name: "Guidy"
        font_size: 25
        
        size_hint: None, None
        size: root.width/10*9.2, root.height/10*0.4
        pos: root.width/ 10*2.9, root.height/10 *9.3

        on_text: root.auto_search(self.text)
    
    TextInput:
        id: genre_search_text
        background_color: 0, 0, 0, 0  # Прозрачный фон самого TextInput
        foreground_color: 0, 0, 0, 1  # Цвет текста - черный
        cursor_color: 0, 0, 0, 1  # Цвет курсора
        padding: [10, 6]  # Отступы для текста
        multiline: False

        # hint_text: "Жанр..."
        # hint_text_color: 136/255, 136/255, 136/255, 1
        font_name: "Guidy"
        font_size: 25
        
        size_hint: None, None
        pos: root.width/ 10*4, root.height/10 *7.22
        size: root.width/10*2, root.height/10*0.4
        on_text: root.genre_change()
        
    Label:
        color: (136/255,136/255,136/255)
        font_size: 25
        size_hint: None, None
        size: root.width/10, root.height/10 * 0.4
        text: 'Фильтры:'
        pos: root.width / 10 * 2.9 , root.height/10 * 8.65
        font_name: "Guidy"
        
        
    # Кнопка для работы с dropdown

    Button:
        id: status_button
        background_color: 0, 0, 0, 0  # Прозрачный фон
        canvas.before:
            Color:
                rgba: 136/255,136/255,136/255, 1  # Цвет кнопки
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [12,]
        text: 'Все'
        size_hint: None, None
        size: root.width/10*1.2, root.height/38
        pos: root.width / 10 * 4 , root.height/10 * 8.17
        # background_color: 136/255,136/255,136/255, 1
        background_normal: ''
        color: 1, 1, 1, 1
        font_name: "Guidy"
        font_size: 20
        on_release: root.open_status_dropdown()

    CustomLayotForRating:
        id:rating_layout
        pos: root.width / 10 * 4 , root.height/10 * 7.7
        on_selected_rating: root.on_rating_selected(args[1])




    CustomButtonWith2States:
        size_hint: (None, None)
        size: root.width/10*0.25, root.height/10*0.34
        mipmap: True
        fit_mode: "fill"
        pos:  root.width / 10 * 5.5, root.height/10 * 7.7
        normal_source: root.normal_del_res
        down_source: root.down_del_res
        on_release: root.recet_filters()

    CustomButtonWith2States:
        size_hint: (None, None)
        size: root.width/10*0.25, root.height/10*0.34
        mipmap: True
        fit_mode: "fill"
        pos:  root.width / 10 * 6, root.height/10 * 7.7
        normal_source: root.normal_decrease_res
        down_source: root.down_decrease_res
        on_release: root.decrease_on_realise()


    CustomButtonWith2States:
        size_hint: (None, None)
        size: root.width/10*0.25, root.height/10*0.34
        mipmap: True
        fit_mode: "fill"
        pos:  root.width / 10 * 6.3, root.height/10 * 7.7
        normal_source: root.normal_increase_res
        down_source: root.down_increase_res
        on_release: root.increase_on_realise()


    RV:
        id: scroll_menu
        
        pos_hint: {'center_x': 0.5, 'top': 0.7}
        size_hint: 0.93, 0.7