<CustomDropdownButtonAdd>:
    background_color: 0, 0, 0, 0  # Прозрачный фон
    canvas.before:
        Color:
            rgba: 136/255,136/255,136/255,1  # Цвет кнопки
        RoundedRectangle:
            pos: self.pos  # Убрали смещение - используем обычную позицию
            size: self.size  # Убрали уменьшение высоты
            radius: [dp(15),]  # Упростили радиус

    background_normal: ''
    font_size: 20
    color: 1, 1, 1, 1
    font_name: "Guidy"
    size_hint_y: None
    height: 36  # ИСПРАВЛЕНО: числовое значение вместо строки
    

<StatusDropdownAdd>:
    canvas.before:
        Color:
            rgba: 136/255,136/255,136/255,0
        Rectangle:
            pos: self.pos
            size: self.size