<CustomDropdownButton>:
    background_color: 0, 0, 0, 0  
    canvas.before:
        Color:
            rgba: 136/255,136/255,136/255,1  
        RoundedRectangle:
            pos: self.pos  
            size: self.size 
            radius: [dp(12),]
    background_normal: ''
    color: 1, 1, 1, 1
    font_name: "Guidy"
    font_size: '20sp'
    size_hint_y: None
    height: dp(25)  
    

<StatusDropdown>:
    canvas.before:
        Color:
            rgba: 136/255,136/255,136/255,0
        Rectangle:
            pos: self.pos
            size: self.size
    margin: [0, dp(1), 0, dp(1)]

<CustomDropdownButtonAdd>:
    background_color: 0, 0, 0, 0  
    canvas.before:
        Color:
            rgba: 136/255,136/255,136/255,1 
        RoundedRectangle:
            pos: self.pos  
            size: self.size  
            radius: [dp(15),]  

    background_normal: ''
    font_size: '20sp'
    color: 1, 1, 1, 1
    font_name: "Guidy"
    size_hint_y: None
    height: dp(36)