<myLayout>:
    
    search_text: search_text
    status_button: status_button 
    rating_layout: rating_layout 
    scroll_menu: scroll_menu
    genre_search_text: genre_search_text
    canvas: 
        Rectangle: 
            pos: self.pos
            size: self.size
        Color:
            rgba: 230/255, 230/255, 230/255, 1
        RoundedRectangle:
            pos: root.width/ 10*2.9, root.height/10 *9.3
            size: root.width/10*9.2, root.height/10*0.4
            radius: [dp(15),]
        RoundedRectangle:
            pos: root.width/ 10*4, root.height/10 *7.22
            size: root.width/10*2, root.height/10*0.4
            radius: [dp(15),]
    
    Label:
        color: (136/255,136/255,136/255)
        font_size: '25sp'
        size_hint: 1/10, 0.4/10
        text: 'Статус:'
        pos_hint: {"x": 0.28/10, "y": 8.11/10}
        font_name: "Guidy"
        
        canvas.before:
            Color:
                rgba: 1, 0, 0, 0 
            Rectangle:
                pos: self.pos
                size: self.size
    Label:
        color: (136/255,136/255,136/255)
        font_size: '25sp'
        text: 'Рейтинг:'
        size_hint: 1/10, 0.4/10
        pos_hint: {"x": 0.36/10, "y": 7.65/10}
        font_name: "Guidy"
    Label:
        color: (136/255,136/255,136/255)
        font_size: '25sp'
        text: 'Жанр:'
        size_hint: 1/10, 0.4/10
        pos_hint: {"x": 0.22/10, "y": 7.22/10}
        font_name: "Guidy"

    TextInput:
        id: search_text
        background_color: 0, 0, 0, 0  # Прозрачный фон самого TextInput
        foreground_color: 0, 0, 0, 1  # Цвет текста - черный
        cursor_color: 0, 0, 0, 1  # Цвет курсора
        padding: [dp(10), dp(6)]  # Отступы для текста
        multiline: False

        hint_text: "Поиск..."
        hint_text_color: 136/255, 136/255, 136/255, 1
        font_name: "Guidy"
        font_size: '25sp'
        
        size_hint: 9.2/10, 0.4/10
        pos_hint: {"x": 0.4/10, "y": 9.3/10}

        on_text: root.auto_search(self.text)
    
    TextInput:
        id: genre_search_text
        background_color: 0, 0, 0, 0  # Прозрачный фон самого TextInput
        foreground_color: 0, 0, 0, 1  # Цвет текста - черный
        cursor_color: 0, 0, 0, 1  # Цвет курсора
        padding: [dp(10), dp(6)]  # Отступы для текста
        multiline: False
        font_name: "Guidy"
        font_size: '25sp'
        
        pos_hint: {"x": 0.4/10, "y": 7.22/10}
        size_hint: 2/10, 0.4/10
        on_text: root.genre_change()
        
    Label:
        color: (136/255,136/255,136/255)
        font_size: '25sp'
        size_hint: 1/10, 0.4/10
        text: 'Фильтры:'
        pos_hint: {"x": 0.4/10, "y": 8.65/10}
        font_name: "Guidy"
        
    Button:
        id: status_button
        background_color: 0, 0, 0, 0  # Прозрачный фон
        canvas.before:
            Color:
                rgba: 136/255,136/255,136/255, 1  # Цвет кнопки
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [dp(12),]
        text: 'Все'
        size_hint: 1.2/10, None
        height: dp(25)
        pos_hint: {"x": 1.5/10, "y": 8.17/10}
        # background_color: 136/255,136/255,136/255, 1
        background_normal: ''
        color: 1, 1, 1, 1
        font_name: "Guidy"
        font_size: '20sp'
        on_release: root.open_status_dropdown()

    CustomLayotForRating:
        id:rating_layout
        pos_hint: {"x": 1.5/10, "y": 7.7/10}
        on_selected_rating: root.on_rating_selected(args[1])
    CustomButtonWith2States:
        size_hint: 0.25/10, 0.34/10
        mipmap: True
        fit_mode: "fill"
        pos_hint: {"x": 3.8/10, "y": 7.25/10}
        normal_source: root.normal_del_res
        down_source: root.down_del_res
        on_release: root.recet_filters()

    CustomButtonWith2States:
        size_hint: 0.25/10, 0.34/10
        mipmap: True
        fit_mode: "fill"
        pos_hint: {"x": 4.4/10, "y": 7.25/10}
        normal_source: root.normal_decrease_res
        down_source: root.down_decrease_res
        on_release: root.decrease_on_realise()

    CustomButtonWith2States:
        size_hint: 0.25/10, 0.34/10
        mipmap: True
        fit_mode: "fill"
        pos_hint: {"x": 4.7/10, "y": 7.25/10}
        normal_source: root.normal_increase_res
        down_source: root.down_increase_res
        on_release: root.increase_on_realise()


    RV:
        id: scroll_menu
        
        pos_hint: {'center_x': 0.5, 'top': 0.7}
        size_hint: 0.93, 0.7