<CustomRatingImage>:
    mipmap: True
    size_hint: None, None
    size: dp(30), dp(30)
    fit_mode: "fill"

<StatefulLabel>:
    orientation: 'horizontal'
    size_hint_y: None
    height: dp(40)
    canvas.before:
        Color:
            rgba: 230/255, 230/255, 230/255, 1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(26),]
    Label:
        text: root.name
        font_size: '20sp'
        size_hint_x: 0.2
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        padding: (dp(10),0)
        color: (0,0,0)
    
    Label:
        text: root.genre
        size_hint_x: 0.2
        font_size: '20sp'
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        padding: (dp(10),0)
        color: (0,0,0)
    Label:
        text: root.status
        size_hint_x: 0.15
        font_size: '20sp'
        text_size: self.size
        halign: 'left'
        valign: 'middle'
        padding: (dp(10),0)
        color: (0,0,0)
    AnchorLayout:
        size_hint_x: 0.1
        anchor_x: 'left'
        anchor_y: 'center'
        BoxLayout:
            size_hint: 1, None
            height: dp(30)
            spacing: dp(5)
            
            CustomRatingImage:
                id: rating_btn_1
            CustomRatingImage:
                id: rating_btn_2
            CustomRatingImage:
                id: rating_btn_3
            CustomRatingImage:
                id: rating_btn_4
            CustomRatingImage:
                id: rating_btn_5

    Widget:
        size_hint_x: 0.07
        
    
    AnchorLayout:
        size_hint_x: 0.065
        anchor_x: 'left'
        anchor_y: 'center'
        BoxLayout:
            size_hint: 0.75, 0.75
            height: dp(30)
            spacing: dp(5)
            
            CustomButtonWith2States:
                size_hint: 0.5,1

                mipmap: True
                fit_mode: "fill"

                normal_source: root.normal_redact_res
                down_source: root.down_redact_res
                on_release: root.go_to_update_film()
            
            CustomButtonWith2States:
                size_hint_x: 0.5
                mipmap: True
                fit_mode: "fill"
                normal_source: root.normal_del_res
                down_source: root.down_del_res
                on_release: root.del_btn_realise(self)

<RV>:
    viewclass: 'StatefulLabel'
    scroll_type: ['bars', 'content']  # Только вертикальная прокрутка
    bar_width: dp(5)
    bar_margin: dp(-20)
    scroll_y: 1 
    grid_layout: grid_layout_ref
    do_scroll_x: False
    do_scroll_y: True
    MyRecycleGridLayout:
        id: grid_layout_ref
        cols: 1
        size_hint_y: None
        height: self.minimum_height
        default_size_hint: 1, None
        default_size: 0, dp(50)
        spacing: dp(10)
        
        
        canvas:
            Color:
                rgba: 1,1,0, 0
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [dp(26),]